export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../assets/images/pizzaIcon.png"),
  },
  {
    id: 2,
    name: "Burger",
    image: require("../assets/images/hamburger.png"),
  },
  {
    id: 3,
    name: "Drinks",
    image: require("../assets/images/drink.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../assets/images/box.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../assets/images/spaghetti.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../assets/images/cupcake.png"),
  },
];

export const featured = [
  {
    id: 1,
    title: "Hot and Spicy",
    description: "soft and tender fried chicken",
    restaurants: [
      {
        id: 1,
        name: "Papa Johns",
        image: require("../assets/images/pizza.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 2,
        name: "KFC",
        image: require("../assets/images/kfc.png"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Fast Food",
        image: require("../assets/images/fast-food.png"),
        description: "Fast Food",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Burger",
    description: "Hot Burgers",
    restaurants: [
      {
        id: 1,
        name: "Papa Johns",
        image: require("../assets/images/burgers.jpeg"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 2,
        name: "Burger King",
        image: require("../assets/images/burgers2.jpg"),
        description: "Hot and spicy pizzas",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Bobby Burger",
        image: require("../assets/images/burgers3.jpg"),
        description: "Fast Food",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Noodles",
    description: "Chinese Cousine",
    restaurants: [
      {
        id: 1,
        name: "Dumpling",
        image: require("../assets/images/thai.jpg"),
        description: "Thai Table",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 2,
        name: "Ramen",
        image: require("../assets/images/thai2.jpg"),
        description: "Ramens with different tastes",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
      {
        id: 3,
        name: "Shrimps pasta",
        image: require("../assets/images/thai3.png"),
        description: "Pasta with Shrimps",
        lng: -85.5324269,
        lat: 38.2145602,
        address: "434 second street",
        stars: 4,
        reviews: "4.4k",
        category: "Fast Food",
        dishes: [
          {
            id: 1,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 2,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
          {
            id: 3,
            name: "pizza",
            description: "cheezy garlic pizza",
            price: 10,
            image: require("../assets/images/pizzaDish.png"),
          },
        ],
      },
    ],
  },
];
